trigger:
  - main

pool:
  name: agent

stages:
  - stage: TerraformInstall
    displayName: "Install Terraform"

    jobs:
      - job: InstallTerraform
        displayName: "Terraform Install Job"

        steps:
          - script: |
              set -e

              echo "Installing Terraform..."

              TF_VERSION="1.8.5"

              sudo apt-get update -y
              sudo apt-get install -y wget unzip

              wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip

              unzip terraform_${TF_VERSION}_linux_amd64.zip

              sudo mv terraform /usr/local/bin/

              terraform version
            displayName: "Install Terraform"

  - stage: TerraformInit
    displayName: "Terraform Init"
    dependsOn: TerraformInstall

    jobs:
      - job: InitTerraform
        displayName: "Terraform Init Job"

        steps:
          - checkout: self

          - script: |
              terraform version
              terraform init
            workingDirectory: module/dev
            displayName: "Terraform Init"