trigger:
 branches:
   include:
     - main
     - feature/*

pool:
 vmImage: ubuntu-latest

stages:
  - stage: plan
    jobs:
      - job: plan
        steps:
          
          - template: installinit.yml
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/module/dev'
              environmentServiceNameAzureRM: 'ser1'



