
trigger:
 branches:
   include:
     - main
 paths:
  include:
    - dev/**
       
pool:
  vmImage: ubuntu-latest

stages:
- stage: terraforminstall
  jobs: 
  - job: terraforminstall
    steps:
    - template: templates/template.yml
    