name: Dev Terraform Pipeline

on:
  workflow_dispatch: {}

  push:
    branches:
      - main
    paths:
      - module/dev/**

permissions:
  id-token: write
  contents: read

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from Dev Pipeline"

  terraform-job:
    uses: ./.github/workflows/terraform-plan-apply.yml
    with:
      working-directory: module/dev
    
    secrets: inherit
          # AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          # AZURE_TENANT_ID : ${{ secrets.AZURE_TENANT_ID }}
          # AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}