name: demoflow

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  hello-job:
    name: Hello Job
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Say Hello
        run: echo "Hello from runner"
  terraforminit-job:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: List repo directory
      #   run: ls -R

          
      - name: Terraform Init
        run: terraform init
        working-directory: module/dev

      - name: terraform-Plan
        run: terraform plan
        working-directory: module/dev

      - name: Terraform apply
        run:  terraform apply --auto-approve
        working-directory: module/dev
    
