name: demoflow

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  hello-job:
    name: Hello Job
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Say Hello
        run: echo "Hello from runner"
  terraforminit-job:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 18519338-f0eb-4983-b06a-38230a388286
          tenant-id: 05605619-5e0b-4c05-bc71-78df7ff48547
          subscription-id: 7551370d-ce64-4050-a442-97a4bfe88e76

      # - name: List repo directory
      #   run: ls -R

          
      - name: Terraform Init
        run: terraform init
        working-directory: module/dev

      - name: terraform-Plan
        run: terraform plan
        working-directory: module/dev
    
