name: demoflow

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  hello-job:
    name: Hello Job
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Say Hello
        run: echo "Hello from runner"
  terraforminit-job:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: c18fa057-ce2e-4d54-9ee4-1f76213c876a
          tenant-id: a6395b74-f5d3-427b-b4c0-5a918ab2e374
          subscription-id: 388a2121-d962-4059-8c36-c24d806cad40
    
